### ISSUE TITLE
关于账号安全

### ISSUE THREAD

**Issue by cyb233** [zfjdhj/mimikkoAutoSignIn#1]
我认为项目中关于账号等信息应该在secrets中保存和读取，以避免意外泄露

**Comment by zfjdhj** [comment]
感谢反馈，已修复

**Comment by cyb233** [comment]
那么现在是需要保存app_id password id Authorization四个值吗？名称直接1234也太随便了2333

兑换能量的助手也可以转移到secrets里方便修改(只有4个code该不会作者是只有4个吧2333)

同时希望增加会员每日抽奖

**Comment by zfjdhj** [comment]
....
可以尝试自己修改嘛

**Comment by cyb233** [comment]
以及可选项，server酱推送，官网是 sc.ftqq.com

**Comment by zfjdhj** [comment]
我有自带的qq bot推送，暂时用不到

**Comment by zfjdhj** [comment]
![image](https://user-images.githubusercontent.com/42639505/104036220-17f6c480-520e-11eb-8a70-d2e40b8cd5dc.png)
像这样
