### ISSUE TITLE
补充助手code

### ISSUE THREAD

**Issue by cyb233** [zfjdhj/mimikkoAutoSignIn#2]
兑换能量的code也是去掉"-aibo"

fileName : 魔女日记
code : nononabook-aibo
 
fileName : 诺诺纳
code : nonona-aibo
 
fileName : 梦梦奈
code : momona-aibo
 
fileName : 爱莉安娜
code : ariana-aibo
 
fileName : 米璐库
code : miruku-aibo
 
fileName : 奈姆利
code : nemuri-aibo
 
fileName : 琉璃
code : ruri-aibo
 
fileName : 阿尔法零
code : alpha0-aibo
 
fileName : 米露可
code : miruku2-aibo
 
fileName : 优莉卡
code : ulrica-aibo

API
查询会员状态get https://api1.mimikko.cn/client/user/GetUserVipInfo
会员抽奖post https://api1.mimikko.cn/client/roll/RollReward

**Comment by zfjdhj** [comment]
作者是个穷逼，只有四个助手，没有会员
有能力者自行修改

**Comment by cyb233** [comment]
> 作者是个穷逼，只有四个助手，没有会员
> 有能力者自行修改

#3
